# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 62680a1b69af6b2b354d5c3151bbdc78fdf43a55af5ac0864c200041dcfe556866e3ef9dbe79581533db1531bea23424f7ab8d7971c4606c279537263bb6b62a

test:
  secret_key_base: 2430091b3dac44575365298180987936756ab4f1a5b678bbb019a83a100d7592d42ac52a2fe58e7f283cbbef8bf083ff2c6e67230efba9052b8b4ed2b7bf1991

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
